name: optcteams
description: A Flutter application for storing teams and how-to's for OPTC.
version: 4.2.2+37

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3
  path: ^1.8.1
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  flutter_launcher_icons: ^0.9.2 # To change: flutter pub run flutter_launcher_icons:main
  shared_preferences: ^2.0.15
  firebase_core: ^1.20.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.6.3
  firebase_analytics: ^9.3.1
  firebase_messaging: ^12.0.2
  flutter_local_notifications: ^9.7.0
  google_mobile_ads: ^2.0.0
  email_validator: ^2.1.17
  intl: ^0.17.0
  google_sign_in: ^5.4.1
  package_info_plus: ^1.4.0
  cached_network_image: ^3.2.1
  easy_localization: ^3.0.1
  json_annotation: ^4.6.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  app_settings: ^4.1.8

dev_dependencies:
  build_runner: ^2.2.0 # flutter pub run build_runner build
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/icon/
    - res/units/
    - res/skills/
    - res/maxed/
    - res/icons/
    - res/potential_abilities/
    - res/info/
    - lib/core/localization/

flutter_icons:
  android: true
  ios: true
  image_path: "res/icon/icon.png"
