name: optcteams
description: A Flutter application for storing teams and how-to's for OPTC.
version: 4.2.6+41

environment:
  sdk: ">=2.19.0 <3.0.0"

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8
  path: ^1.8.2
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  flutter_launcher_icons: ^0.11.0 # To change: flutter pub run flutter_launcher_icons:main
  shared_preferences: ^2.1.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_analytics: ^10.4.1
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.0.0
  google_mobile_ads: ^3.0.0
  email_validator: ^2.1.17
  intl: ^0.18.0
  google_sign_in: ^6.1.0
  package_info_plus: ^4.0.1
  cached_network_image: ^3.2.3
  easy_localization: ^3.0.2
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  app_settings: ^4.2.0
  flutter_dotenv: ^5.0.2
  user_messaging_platform: ^1.2.1

dev_dependencies:
  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/icon/
    - res/units/
    - res/skills/
    - res/maxed/
    - res/icons/
    - res/potential_abilities/
    - res/info/
    - lib/core/localization/
    - res/environment/

flutter_icons:
  android: true
  ios: true
  image_path: "res/icon/icon.png"
